encoding: utf-8

# SEO相关信息
title: 智能生活 - Aikarma's homepage
description: 专业网站托管,外贸soho,个人博客,企业网站,个性化服务,关于我的生活当中的科技智能生活,个人技术分享!-Professional website hosting, foreign trade soho, personal blog, corporate website, personalized service, about my life in the science and technology intelligent life, personal technology sharing!
keywords: TMaize,Blog,Java,Html,JavaScript
author: TMaize
footerText: 'Copyright © 2021 粤ICP备19153392号'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://aikarma.com'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
# tucaoUrl: https://support.qq.com/product/86335

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: 搜租房
    url: https://www.souzufang.com

